// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// control_bus
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of ap_return
//        bit 31~0 - ap_return[31:0] (Read)
// 0x18 : Data signal of rows
//        bit 31~0 - rows[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of cols
//        bit 31~0 - cols[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of rows2
//        bit 31~0 - rows2[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of cols2
//        bit 31~0 - cols2[31:0] (Read/Write)
// 0x34 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XIMAGE_FILTER_CONTROL_BUS_ADDR_AP_CTRL    0x00
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_GIE        0x04
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_IER        0x08
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_ISR        0x0c
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_AP_RETURN  0x10
#define XIMAGE_FILTER_CONTROL_BUS_BITS_AP_RETURN  32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_ROWS_DATA  0x18
#define XIMAGE_FILTER_CONTROL_BUS_BITS_ROWS_DATA  32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_COLS_DATA  0x20
#define XIMAGE_FILTER_CONTROL_BUS_BITS_COLS_DATA  32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_ROWS2_DATA 0x28
#define XIMAGE_FILTER_CONTROL_BUS_BITS_ROWS2_DATA 32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_COLS2_DATA 0x30
#define XIMAGE_FILTER_CONTROL_BUS_BITS_COLS2_DATA 32

