# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/tim/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/tim/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  /home/tim/image_filter/solution1/impl/ip
  /home/tim/image_filter_2/solution1/impl/ip
} [current_project]
add_files /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_3/design_1_processing_system7_0_3.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_0_4/design_1_axi_vdma_0_4.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_0_4/design_1_axi_vdma_0_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_0_4/design_1_axi_vdma_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_3/design_1_rst_processing_system7_0_100M_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_3/design_1_rst_processing_system7_0_100M_3.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_3/design_1_rst_processing_system7_0_100M_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_8/design_1_xbar_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/image_filter_v1_0/5c733e7a/constraints/image_filter_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_1_0/design_1_axi_vdma_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_1_0/design_1_axi_vdma_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_1_0/design_1_axi_vdma_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/image_filter_fh_v1_0/0bac0dc5/constraints/image_filter_fh_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_2_0/design_1_axi_vdma_2_0.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_2_0/design_1_axi_vdma_2_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_2_0/design_1_axi_vdma_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib /home/tim/project_1/project_1.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
read_xdc /home/tim/project_1/project_1.srcs/constrs_1/new/constr.xdc
set_property used_in_implementation false [get_files /home/tim/project_1/project_1.srcs/constrs_1/new/constr.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top design_1_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef design_1_wrapper.dcp
catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
