// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module image_filter_fh_PadImage_480_640_51_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_data_stream_V_dout,
        in_data_stream_V_empty_n,
        in_data_stream_V_read,
        out_data_stream_V_din,
        out_data_stream_V_full_n,
        out_data_stream_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 3'b1;
parameter    ap_ST_pp0_stg0_fsm_1 = 3'b10;
parameter    ap_ST_st6_fsm_2 = 3'b100;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv19_0 = 19'b0000000000000000000;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv19_59949 = 19'b1011001100101001001;
parameter    ap_const_lv19_1 = 19'b1;
parameter    ap_const_lv10_2B3 = 10'b1010110011;
parameter    ap_const_lv10_1 = 10'b1;
parameter    ap_const_lv10_1E0 = 10'b111100000;
parameter    ap_const_lv10_1DF = 10'b111011111;
parameter    ap_const_lv10_280 = 10'b1010000000;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] in_data_stream_V_dout;
input   in_data_stream_V_empty_n;
output   in_data_stream_V_read;
output  [31:0] out_data_stream_V_din;
input   out_data_stream_V_full_n;
output   out_data_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_data_stream_V_read;
reg out_data_stream_V_write;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm = 3'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_22;
reg   [9:0] linebuffer_address0;
reg    linebuffer_ce0;
reg    linebuffer_we0;
wire   [31:0] linebuffer_d0;
wire   [31:0] linebuffer_q0;
reg   [18:0] indvar_flatten_reg_104;
reg   [9:0] i_reg_115;
reg   [9:0] asd_reg_126;
wire   [0:0] exitcond_flatten_fu_152_p2;
reg   [0:0] exitcond_flatten_reg_238;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_1;
reg    ap_sig_bdd_62;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg   [0:0] tmp_reg_258;
reg   [0:0] tmp_2_reg_266;
reg    ap_sig_bdd_78;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_reg_238_pp0_it2;
reg    ap_sig_bdd_88;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_reg_238_pp0_it1;
wire   [18:0] indvar_flatten_next_fu_158_p2;
wire   [9:0] asd_mid2_fu_170_p3;
reg   [9:0] asd_mid2_reg_247;
wire   [9:0] i_mid2_fu_184_p3;
reg   [9:0] i_mid2_reg_253;
wire   [0:0] tmp_fu_192_p2;
reg   [0:0] ap_reg_ppstg_tmp_reg_258_pp0_it1;
wire   [0:0] tmp_s_fu_198_p2;
reg   [0:0] tmp_s_reg_262;
wire   [0:0] tmp_2_fu_204_p2;
reg   [0:0] ap_reg_ppstg_tmp_2_reg_266_pp0_it1;
wire   [9:0] asd_1_fu_210_p2;
reg   [31:0] tmp_6_reg_286;
reg    ap_sig_bdd_144;
reg   [9:0] i_phi_fu_119_p4;
reg   [31:0] ap_reg_phiprechg_tmp_5_reg_137pp0_it2;
reg   [31:0] ap_reg_phiprechg_tmp_5_reg_137pp0_it3;
wire   [31:0] ap_reg_phiprechg_tmp_5_reg_137pp0_it1;
wire   [63:0] tmp_7_fu_219_p1;
wire   [63:0] tmp_8_fu_223_p1;
reg   [31:0] output_1_fu_66;
wire   [0:0] exitcond_fu_164_p2;
wire   [9:0] i_s_fu_178_p2;
reg    ap_sig_cseq_ST_st6_fsm_2;
reg    ap_sig_bdd_248;
reg   [2:0] ap_NS_fsm;
reg    ap_sig_bdd_140;
reg    ap_sig_bdd_170;
reg    ap_sig_bdd_164;
reg    ap_sig_bdd_284;
reg    ap_sig_bdd_283;


image_filter_fh_PadImage_480_640_51_s_linebuffer #(
    .DataWidth( 32 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
linebuffer_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( linebuffer_address0 ),
    .ce0( linebuffer_ce0 ),
    .we0( linebuffer_we0 ),
    .d0( linebuffer_d0 ),
    .q0( linebuffer_q0 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_2)) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3))) & ~(exitcond_flatten_fu_152_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_144)) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3))))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_144)) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)))) begin
            if (~(ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) begin
                ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
            end else if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0)) begin
                ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
            end
        end
    end
end

/// ap_reg_ppiten_pp0_it3 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_144)) begin
            ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten_reg_238 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_reg_258) & (ap_const_lv1_0 == tmp_2_reg_266) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten_reg_238 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_reg_258) & (ap_const_lv1_0 == tmp_2_reg_266) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)))))) begin
        ap_reg_phiprechg_tmp_5_reg_137pp0_it2 <= output_1_fu_66;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3))))) begin
        ap_reg_phiprechg_tmp_5_reg_137pp0_it2 <= ap_reg_phiprechg_tmp_5_reg_137pp0_it1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (ap_sig_bdd_164) begin
        if (ap_sig_bdd_170) begin
            ap_reg_phiprechg_tmp_5_reg_137pp0_it3 <= tmp_6_reg_286;
        end else if (ap_sig_bdd_140) begin
            ap_reg_phiprechg_tmp_5_reg_137pp0_it3 <= linebuffer_q0;
        end else if ((ap_true == ap_true)) begin
            ap_reg_phiprechg_tmp_5_reg_137pp0_it3 <= ap_reg_phiprechg_tmp_5_reg_137pp0_it2;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3))) & (exitcond_flatten_fu_152_p2 == ap_const_lv1_0))) begin
        asd_reg_126 <= asd_1_fu_210_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_144)) begin
        asd_reg_126 <= ap_const_lv10_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten_reg_238 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3))))) begin
        i_reg_115 <= i_mid2_reg_253;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_144)) begin
        i_reg_115 <= ap_const_lv10_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3))) & (exitcond_flatten_fu_152_p2 == ap_const_lv1_0))) begin
        indvar_flatten_reg_104 <= indvar_flatten_next_fu_158_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_144)) begin
        indvar_flatten_reg_104 <= ap_const_lv19_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3))))) begin
        ap_reg_ppstg_exitcond_flatten_reg_238_pp0_it1 <= exitcond_flatten_reg_238;
        ap_reg_ppstg_tmp_2_reg_266_pp0_it1 <= tmp_2_reg_266;
        ap_reg_ppstg_tmp_reg_258_pp0_it1 <= tmp_reg_258;
        exitcond_flatten_reg_238 <= exitcond_flatten_fu_152_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)))) begin
        ap_reg_ppstg_exitcond_flatten_reg_238_pp0_it2 <= ap_reg_ppstg_exitcond_flatten_reg_238_pp0_it1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3))) & (exitcond_flatten_fu_152_p2 == ap_const_lv1_0))) begin
        asd_mid2_reg_247 <= asd_mid2_fu_170_p3;
        tmp_2_reg_266 <= tmp_2_fu_204_p2;
        tmp_reg_258 <= tmp_fu_192_p2;
        tmp_s_reg_262 <= tmp_s_fu_198_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3))) & (exitcond_flatten_fu_152_p2 == ap_const_lv1_0))) begin
        i_mid2_reg_253 <= i_mid2_fu_184_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten_reg_238 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_reg_258) & ~(ap_const_lv1_0 == tmp_2_reg_266) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3))))) begin
        output_1_fu_66 <= in_data_stream_V_dout;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten_reg_238 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_reg_258) & ~(ap_const_lv1_0 == tmp_2_reg_266) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3))))) begin
        tmp_6_reg_286 <= in_data_stream_V_dout;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_st6_fsm_2)
begin
    if (((ap_const_logic_1 == ap_done_reg) | (ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_2))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_sig_cseq_ST_st6_fsm_2)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_2)) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp0_stg0_fsm_1 assign process. ///
always @ (ap_sig_bdd_62)
begin
    if (ap_sig_bdd_62) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_22)
begin
    if (ap_sig_bdd_22) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st6_fsm_2 assign process. ///
always @ (ap_sig_bdd_248)
begin
    if (ap_sig_bdd_248) begin
        ap_sig_cseq_ST_st6_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_2 = ap_const_logic_0;
    end
end

/// i_phi_fu_119_p4 assign process. ///
always @ (i_reg_115 or exitcond_flatten_reg_238 or ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it1 or i_mid2_reg_253)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten_reg_238 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
        i_phi_fu_119_p4 = i_mid2_reg_253;
    end else begin
        i_phi_fu_119_p4 = i_reg_115;
    end
end

/// in_data_stream_V_read assign process. ///
always @ (exitcond_flatten_reg_238 or ap_sig_cseq_ST_pp0_stg0_fsm_1 or tmp_reg_258 or tmp_2_reg_266 or ap_sig_bdd_78 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_88 or ap_reg_ppiten_pp0_it3)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten_reg_238 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_reg_258) & ~(ap_const_lv1_0 == tmp_2_reg_266) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3))))) begin
        in_data_stream_V_read = ap_const_logic_1;
    end else begin
        in_data_stream_V_read = ap_const_logic_0;
    end
end

/// linebuffer_address0 assign process. ///
always @ (tmp_reg_258 or tmp_7_fu_219_p1 or tmp_8_fu_223_p1 or ap_sig_bdd_284 or ap_sig_bdd_283)
begin
    if (ap_sig_bdd_283) begin
        if (ap_sig_bdd_284) begin
            linebuffer_address0 = tmp_8_fu_223_p1;
        end else if ((ap_const_lv1_0 == tmp_reg_258)) begin
            linebuffer_address0 = tmp_7_fu_219_p1;
        end else begin
            linebuffer_address0 = 'bx;
        end
    end else begin
        linebuffer_address0 = 'bx;
    end
end

/// linebuffer_ce0 assign process. ///
always @ (exitcond_flatten_reg_238 or ap_sig_cseq_ST_pp0_stg0_fsm_1 or tmp_reg_258 or tmp_2_reg_266 or ap_sig_bdd_78 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_88 or ap_reg_ppiten_pp0_it3 or tmp_s_reg_262)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten_reg_238 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_reg_258) & ~(ap_const_lv1_0 == tmp_2_reg_266) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten_reg_238 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_reg_258) & ~(ap_const_lv1_0 == tmp_2_reg_266) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3))) & ~(ap_const_lv1_0 == tmp_s_reg_262)))) begin
        linebuffer_ce0 = ap_const_logic_1;
    end else begin
        linebuffer_ce0 = ap_const_logic_0;
    end
end

/// linebuffer_we0 assign process. ///
always @ (exitcond_flatten_reg_238 or ap_sig_cseq_ST_pp0_stg0_fsm_1 or tmp_reg_258 or tmp_2_reg_266 or ap_sig_bdd_78 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_88 or ap_reg_ppiten_pp0_it3 or tmp_s_reg_262)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten_reg_238 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_reg_258) & ~(ap_const_lv1_0 == tmp_2_reg_266) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3))) & ~(ap_const_lv1_0 == tmp_s_reg_262))) begin
        linebuffer_we0 = ap_const_logic_1;
    end else begin
        linebuffer_we0 = ap_const_logic_0;
    end
end

/// out_data_stream_V_write assign process. ///
always @ (ap_sig_bdd_78 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_flatten_reg_238_pp0_it2 or ap_sig_bdd_88 or ap_reg_ppiten_pp0_it3)
begin
    if (((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten_reg_238_pp0_it2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3))))) begin
        out_data_stream_V_write = ap_const_logic_1;
    end else begin
        out_data_stream_V_write = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_CS_fsm or ap_sig_cseq_ST_pp0_stg0_fsm_1 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_78 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_88 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_144)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_144) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_pp0_stg0_fsm_1 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) & ~((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2)))) begin
                ap_NS_fsm = ap_ST_st6_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end
        end
        ap_ST_st6_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_reg_phiprechg_tmp_5_reg_137pp0_it1 = 'bx;

/// ap_sig_bdd_140 assign process. ///
always @ (ap_reg_ppstg_exitcond_flatten_reg_238_pp0_it1 or ap_reg_ppstg_tmp_reg_258_pp0_it1 or ap_reg_ppstg_tmp_2_reg_266_pp0_it1)
begin
    ap_sig_bdd_140 = ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten_reg_238_pp0_it1) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_reg_258_pp0_it1) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_2_reg_266_pp0_it1));
end

/// ap_sig_bdd_144 assign process. ///
always @ (ap_start or ap_done_reg)
begin
    ap_sig_bdd_144 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end

/// ap_sig_bdd_164 assign process. ///
always @ (ap_sig_bdd_78 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_88 or ap_reg_ppiten_pp0_it3)
begin
    ap_sig_bdd_164 = ((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_78 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_88 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3))));
end

/// ap_sig_bdd_170 assign process. ///
always @ (ap_reg_ppstg_exitcond_flatten_reg_238_pp0_it1 or ap_reg_ppstg_tmp_reg_258_pp0_it1 or ap_reg_ppstg_tmp_2_reg_266_pp0_it1)
begin
    ap_sig_bdd_170 = ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten_reg_238_pp0_it1) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_2_reg_266_pp0_it1) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_reg_258_pp0_it1));
end

/// ap_sig_bdd_22 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_22 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_248 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_248 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_283 assign process. ///
always @ (exitcond_flatten_reg_238 or ap_sig_cseq_ST_pp0_stg0_fsm_1 or tmp_2_reg_266 or ap_reg_ppiten_pp0_it1)
begin
    ap_sig_bdd_283 = ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten_reg_238 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_2_reg_266) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1));
end

/// ap_sig_bdd_284 assign process. ///
always @ (tmp_reg_258 or tmp_s_reg_262)
begin
    ap_sig_bdd_284 = (~(ap_const_lv1_0 == tmp_reg_258) & ~(ap_const_lv1_0 == tmp_s_reg_262));
end

/// ap_sig_bdd_62 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_62 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

/// ap_sig_bdd_78 assign process. ///
always @ (in_data_stream_V_empty_n or exitcond_flatten_reg_238 or tmp_reg_258 or tmp_2_reg_266)
begin
    ap_sig_bdd_78 = ((in_data_stream_V_empty_n == ap_const_logic_0) & (exitcond_flatten_reg_238 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_reg_258) & ~(ap_const_lv1_0 == tmp_2_reg_266));
end

/// ap_sig_bdd_88 assign process. ///
always @ (out_data_stream_V_full_n or ap_reg_ppstg_exitcond_flatten_reg_238_pp0_it2)
begin
    ap_sig_bdd_88 = ((out_data_stream_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_flatten_reg_238_pp0_it2));
end
assign asd_1_fu_210_p2 = (asd_mid2_fu_170_p3 + ap_const_lv10_1);
assign asd_mid2_fu_170_p3 = ((exitcond_fu_164_p2[0:0]===1'b1)? ap_const_lv10_0: asd_reg_126);
assign exitcond_flatten_fu_152_p2 = (indvar_flatten_reg_104 == ap_const_lv19_59949? 1'b1: 1'b0);
assign exitcond_fu_164_p2 = (asd_reg_126 == ap_const_lv10_2B3? 1'b1: 1'b0);
assign i_mid2_fu_184_p3 = ((exitcond_fu_164_p2[0:0]===1'b1)? i_s_fu_178_p2: i_phi_fu_119_p4);
assign i_s_fu_178_p2 = (i_phi_fu_119_p4 + ap_const_lv10_1);
assign indvar_flatten_next_fu_158_p2 = (indvar_flatten_reg_104 + ap_const_lv19_1);
assign linebuffer_d0 = in_data_stream_V_dout;
assign out_data_stream_V_din = ap_reg_phiprechg_tmp_5_reg_137pp0_it3;
assign tmp_2_fu_204_p2 = (asd_mid2_fu_170_p3 < ap_const_lv10_280? 1'b1: 1'b0);
assign tmp_7_fu_219_p1 = asd_mid2_reg_247;
assign tmp_8_fu_223_p1 = asd_mid2_reg_247;
assign tmp_fu_192_p2 = (i_mid2_fu_184_p3 < ap_const_lv10_1E0? 1'b1: 1'b0);
assign tmp_s_fu_198_p2 = (i_mid2_fu_184_p3 == ap_const_lv10_1DF? 1'b1: 1'b0);


endmodule //image_filter_fh_PadImage_480_640_51_s

