// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="image_filter,hls_ip_2015_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=6.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=6.472000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=68,HLS_SYN_DSP=45,HLS_SYN_FF=20990,HLS_SYN_LUT=23319}" *)

module image_filter (
        s_axi_control_bus_AWVALID,
        s_axi_control_bus_AWREADY,
        s_axi_control_bus_AWADDR,
        s_axi_control_bus_WVALID,
        s_axi_control_bus_WREADY,
        s_axi_control_bus_WDATA,
        s_axi_control_bus_WSTRB,
        s_axi_control_bus_ARVALID,
        s_axi_control_bus_ARREADY,
        s_axi_control_bus_ARADDR,
        s_axi_control_bus_RVALID,
        s_axi_control_bus_RREADY,
        s_axi_control_bus_RDATA,
        s_axi_control_bus_RRESP,
        s_axi_control_bus_BVALID,
        s_axi_control_bus_BREADY,
        s_axi_control_bus_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        input_stream_TDATA,
        input_stream_TKEEP,
        input_stream_TSTRB,
        input_stream_TUSER,
        input_stream_TLAST,
        input_stream_TID,
        input_stream_TDEST,
        input2_TDATA,
        input2_TKEEP,
        input2_TSTRB,
        input2_TUSER,
        input2_TLAST,
        input2_TID,
        input2_TDEST,
        input_stream_TVALID,
        input_stream_TREADY,
        input2_TVALID,
        input2_TREADY
);

parameter    C_S_AXI_CONTROL_BUS_DATA_WIDTH = 32;
parameter    ap_const_int64_8 = 8;
parameter    C_S_AXI_CONTROL_BUS_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_true = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    C_S_AXI_CONTROL_BUS_WSTRB_WIDTH = (C_S_AXI_CONTROL_BUS_DATA_WIDTH / ap_const_int64_8);
parameter    C_S_AXI_WSTRB_WIDTH = (C_S_AXI_DATA_WIDTH / ap_const_int64_8);

input   s_axi_control_bus_AWVALID;
output   s_axi_control_bus_AWREADY;
input  [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1 : 0] s_axi_control_bus_AWADDR;
input   s_axi_control_bus_WVALID;
output   s_axi_control_bus_WREADY;
input  [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1 : 0] s_axi_control_bus_WDATA;
input  [C_S_AXI_CONTROL_BUS_WSTRB_WIDTH - 1 : 0] s_axi_control_bus_WSTRB;
input   s_axi_control_bus_ARVALID;
output   s_axi_control_bus_ARREADY;
input  [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1 : 0] s_axi_control_bus_ARADDR;
output   s_axi_control_bus_RVALID;
input   s_axi_control_bus_RREADY;
output  [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1 : 0] s_axi_control_bus_RDATA;
output  [1:0] s_axi_control_bus_RRESP;
output   s_axi_control_bus_BVALID;
input   s_axi_control_bus_BREADY;
output  [1:0] s_axi_control_bus_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input  [31:0] input_stream_TDATA;
input  [3:0] input_stream_TKEEP;
input  [3:0] input_stream_TSTRB;
input  [0:0] input_stream_TUSER;
input  [0:0] input_stream_TLAST;
input  [0:0] input_stream_TID;
input  [0:0] input_stream_TDEST;
input  [31:0] input2_TDATA;
input  [3:0] input2_TKEEP;
input  [3:0] input2_TSTRB;
input  [0:0] input2_TUSER;
input  [0:0] input2_TLAST;
input  [0:0] input2_TID;
input  [0:0] input2_TDEST;
input   input_stream_TVALID;
output   input_stream_TREADY;
input   input2_TVALID;
output   input2_TREADY;

reg    ap_rst_n_inv;
wire    image_filter_control_bus_s_axi_U_ap_dummy_ce;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
reg    ap_idle;
wire   [31:0] ap_return;
wire   [31:0] rows;
wire   [31:0] cols;
wire   [31:0] rows2;
wire   [31:0] cols2;
wire    image_filter_Block_Mat_exit2020_proc_U0_ap_start;
wire    image_filter_Block_Mat_exit2020_proc_U0_ap_done;
reg    image_filter_Block_Mat_exit2020_proc_U0_ap_continue;
wire    image_filter_Block_Mat_exit2020_proc_U0_ap_idle;
wire    image_filter_Block_Mat_exit2020_proc_U0_ap_ready;
wire   [31:0] image_filter_Block_Mat_exit2020_proc_U0_rows;
wire   [31:0] image_filter_Block_Mat_exit2020_proc_U0_cols;
wire   [31:0] image_filter_Block_Mat_exit2020_proc_U0_rows2;
wire   [31:0] image_filter_Block_Mat_exit2020_proc_U0_cols2;
wire   [11:0] image_filter_Block_Mat_exit2020_proc_U0_ap_return_0;
wire   [11:0] image_filter_Block_Mat_exit2020_proc_U0_ap_return_1;
wire   [11:0] image_filter_Block_Mat_exit2020_proc_U0_ap_return_2;
wire   [11:0] image_filter_Block_Mat_exit2020_proc_U0_ap_return_3;
wire   [11:0] image_filter_Block_Mat_exit2020_proc_U0_ap_return_4;
wire   [11:0] image_filter_Block_Mat_exit2020_proc_U0_ap_return_5;
wire   [11:0] image_filter_Block_Mat_exit2020_proc_U0_ap_return_6;
wire   [11:0] image_filter_Block_Mat_exit2020_proc_U0_ap_return_7;
wire   [11:0] image_filter_Block_Mat_exit2020_proc_U0_ap_return_8;
wire   [11:0] image_filter_Block_Mat_exit2020_proc_U0_ap_return_9;
reg    ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_2_rows_V_channel;
wire    img_0_2_rows_V_channel_full_n;
reg    ap_reg_ready_img_0_2_rows_V_channel_full_n = 1'b0;
reg    ap_sig_ready_img_0_2_rows_V_channel_full_n;
reg    ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_1_rows_V_channel;
wire    img_0_1_rows_V_channel_full_n;
reg    ap_reg_ready_img_0_1_rows_V_channel_full_n = 1'b0;
reg    ap_sig_ready_img_0_1_rows_V_channel_full_n;
reg    ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_1_rows_V_channel1;
wire    img_0_1_rows_V_channel1_full_n;
reg    ap_reg_ready_img_0_1_rows_V_channel1_full_n = 1'b0;
reg    ap_sig_ready_img_0_1_rows_V_channel1_full_n;
reg    ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_1_cols_V_channel;
wire    img_0_1_cols_V_channel_full_n;
reg    ap_reg_ready_img_0_1_cols_V_channel_full_n = 1'b0;
reg    ap_sig_ready_img_0_1_cols_V_channel_full_n;
reg    ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_resized_cols_V_channel1;
wire    img_resized_cols_V_channel1_full_n;
reg    ap_reg_ready_img_resized_cols_V_channel1_full_n = 1'b0;
reg    ap_sig_ready_img_resized_cols_V_channel1_full_n;
reg    ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_1_cols_V_channel1;
wire    img_0_1_cols_V_channel1_full_n;
reg    ap_reg_ready_img_0_1_cols_V_channel1_full_n = 1'b0;
reg    ap_sig_ready_img_0_1_cols_V_channel1_full_n;
reg    ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_resized_rows_V_channel;
wire    img_resized_rows_V_channel_full_n;
reg    ap_reg_ready_img_resized_rows_V_channel_full_n = 1'b0;
reg    ap_sig_ready_img_resized_rows_V_channel_full_n;
reg    ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_resized_rows_V_channel1;
wire    img_resized_rows_V_channel1_full_n;
reg    ap_reg_ready_img_resized_rows_V_channel1_full_n = 1'b0;
reg    ap_sig_ready_img_resized_rows_V_channel1_full_n;
reg    ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_resized_cols_V_channel;
wire    img_resized_cols_V_channel_full_n;
reg    ap_reg_ready_img_resized_cols_V_channel_full_n = 1'b0;
reg    ap_sig_ready_img_resized_cols_V_channel_full_n;
reg    ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_2_cols_V_channel;
wire    img_0_2_cols_V_channel_full_n;
reg    ap_reg_ready_img_0_2_cols_V_channel_full_n = 1'b0;
reg    ap_sig_ready_img_0_2_cols_V_channel_full_n;
wire    image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_start;
wire    image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_done;
wire    image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_continue;
wire    image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_idle;
wire    image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready;
wire   [31:0] image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TDATA;
wire    image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TVALID;
wire    image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TREADY;
wire   [3:0] image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TKEEP;
wire   [3:0] image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TSTRB;
wire   [0:0] image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TUSER;
wire   [0:0] image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TLAST;
wire   [0:0] image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TID;
wire   [0:0] image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TDEST;
wire   [11:0] image_filter_AXIvideo2Mat_32_480_640_5_U0_img_rows_V_read;
wire   [11:0] image_filter_AXIvideo2Mat_32_480_640_5_U0_img_cols_V_read;
wire   [31:0] image_filter_AXIvideo2Mat_32_480_640_5_U0_img_data_stream_V_din;
wire    image_filter_AXIvideo2Mat_32_480_640_5_U0_img_data_stream_V_full_n;
wire    image_filter_AXIvideo2Mat_32_480_640_5_U0_img_data_stream_V_write;
wire    image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_start;
wire    image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_done;
wire    image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_continue;
wire    image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_idle;
wire    image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready;
wire   [31:0] image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TDATA;
wire    image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TVALID;
wire    image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TREADY;
wire   [3:0] image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TKEEP;
wire   [3:0] image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TSTRB;
wire   [0:0] image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TUSER;
wire   [0:0] image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TLAST;
wire   [0:0] image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TID;
wire   [0:0] image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TDEST;
wire   [11:0] image_filter_AXIvideo2Mat_32_480_640_5_1_U0_img_rows_V_read;
wire   [11:0] image_filter_AXIvideo2Mat_32_480_640_5_1_U0_img_cols_V_read;
wire   [31:0] image_filter_AXIvideo2Mat_32_480_640_5_1_U0_img_data_stream_V_din;
wire    image_filter_AXIvideo2Mat_32_480_640_5_1_U0_img_data_stream_V_full_n;
wire    image_filter_AXIvideo2Mat_32_480_640_5_1_U0_img_data_stream_V_write;
wire    image_filter_Resize_Test_U0_ap_start;
wire    image_filter_Resize_Test_U0_ap_done;
wire    image_filter_Resize_Test_U0_ap_continue;
wire    image_filter_Resize_Test_U0_ap_idle;
wire    image_filter_Resize_Test_U0_ap_ready;
wire   [11:0] image_filter_Resize_Test_U0_p_src_rows_V_read;
wire   [11:0] image_filter_Resize_Test_U0_p_src_cols_V_read;
wire   [31:0] image_filter_Resize_Test_U0_p_src_data_stream_V_dout;
wire    image_filter_Resize_Test_U0_p_src_data_stream_V_empty_n;
wire    image_filter_Resize_Test_U0_p_src_data_stream_V_read;
wire   [11:0] image_filter_Resize_Test_U0_p_dst_rows_V_read;
wire   [11:0] image_filter_Resize_Test_U0_p_dst_cols_V_read;
wire   [31:0] image_filter_Resize_Test_U0_p_dst_data_stream_V_din;
wire    image_filter_Resize_Test_U0_p_dst_data_stream_V_full_n;
wire    image_filter_Resize_Test_U0_p_dst_data_stream_V_write;
wire    image_filter_Loop_1_proc_U0_ap_start;
wire    image_filter_Loop_1_proc_U0_ap_done;
wire    image_filter_Loop_1_proc_U0_ap_continue;
wire    image_filter_Loop_1_proc_U0_ap_idle;
wire    image_filter_Loop_1_proc_U0_ap_ready;
wire   [31:0] image_filter_Loop_1_proc_U0_img_resized_data_stream_0_V_dout;
wire    image_filter_Loop_1_proc_U0_img_resized_data_stream_0_V_empty_n;
wire    image_filter_Loop_1_proc_U0_img_resized_data_stream_0_V_read;
wire   [31:0] image_filter_Loop_1_proc_U0_img_0_2_data_stream_0_V_dout;
wire    image_filter_Loop_1_proc_U0_img_0_2_data_stream_0_V_empty_n;
wire    image_filter_Loop_1_proc_U0_img_0_2_data_stream_0_V_read;
wire   [11:0] image_filter_Loop_1_proc_U0_p_read;
wire   [11:0] image_filter_Loop_1_proc_U0_p_read1;
wire   [63:0] image_filter_Loop_1_proc_U0_ap_return;
wire    ap_chn_write_image_filter_Loop_1_proc_U0_tmp_loc_channel;
wire    tmp_loc_channel_full_n;
wire    image_filter_Block_loopexit24_i_proc1_U0_ap_start;
wire    image_filter_Block_loopexit24_i_proc1_U0_ap_done;
wire    image_filter_Block_loopexit24_i_proc1_U0_ap_continue;
wire    image_filter_Block_loopexit24_i_proc1_U0_ap_idle;
wire    image_filter_Block_loopexit24_i_proc1_U0_ap_ready;
wire   [63:0] image_filter_Block_loopexit24_i_proc1_U0_p_read;
wire   [31:0] image_filter_Block_loopexit24_i_proc1_U0_ap_return;
wire    ap_chn_write_image_filter_Block_loopexit24_i_proc1_U0_p_0_i_i_loc_channel;
wire    p_0_i_i_loc_channel_full_n;
wire    image_filter_sqrtf1_U0_ap_start;
wire    image_filter_sqrtf1_U0_ap_done;
wire    image_filter_sqrtf1_U0_ap_continue;
wire    image_filter_sqrtf1_U0_ap_idle;
wire    image_filter_sqrtf1_U0_ap_ready;
wire   [31:0] image_filter_sqrtf1_U0_p_read;
wire   [31:0] image_filter_sqrtf1_U0_ap_return;
wire    ap_sig_hs_continue;
wire    img_0_1_rows_V_channel_U_ap_dummy_ce;
wire   [11:0] img_0_1_rows_V_channel_din;
wire    img_0_1_rows_V_channel_write;
wire   [11:0] img_0_1_rows_V_channel_dout;
wire    img_0_1_rows_V_channel_empty_n;
wire    img_0_1_rows_V_channel_read;
wire    img_0_1_rows_V_channel1_U_ap_dummy_ce;
wire   [11:0] img_0_1_rows_V_channel1_din;
wire    img_0_1_rows_V_channel1_write;
wire   [11:0] img_0_1_rows_V_channel1_dout;
wire    img_0_1_rows_V_channel1_empty_n;
wire    img_0_1_rows_V_channel1_read;
wire    img_0_1_cols_V_channel_U_ap_dummy_ce;
wire   [11:0] img_0_1_cols_V_channel_din;
wire    img_0_1_cols_V_channel_write;
wire   [11:0] img_0_1_cols_V_channel_dout;
wire    img_0_1_cols_V_channel_empty_n;
wire    img_0_1_cols_V_channel_read;
wire    img_0_1_cols_V_channel1_U_ap_dummy_ce;
wire   [11:0] img_0_1_cols_V_channel1_din;
wire    img_0_1_cols_V_channel1_write;
wire   [11:0] img_0_1_cols_V_channel1_dout;
wire    img_0_1_cols_V_channel1_empty_n;
wire    img_0_1_cols_V_channel1_read;
wire    img_resized_rows_V_channel_U_ap_dummy_ce;
wire   [11:0] img_resized_rows_V_channel_din;
wire    img_resized_rows_V_channel_write;
wire   [11:0] img_resized_rows_V_channel_dout;
wire    img_resized_rows_V_channel_empty_n;
wire    img_resized_rows_V_channel_read;
wire    img_resized_rows_V_channel1_U_ap_dummy_ce;
wire   [11:0] img_resized_rows_V_channel1_din;
wire    img_resized_rows_V_channel1_write;
wire   [11:0] img_resized_rows_V_channel1_dout;
wire    img_resized_rows_V_channel1_empty_n;
wire    img_resized_rows_V_channel1_read;
wire    img_resized_cols_V_channel_U_ap_dummy_ce;
wire   [11:0] img_resized_cols_V_channel_din;
wire    img_resized_cols_V_channel_write;
wire   [11:0] img_resized_cols_V_channel_dout;
wire    img_resized_cols_V_channel_empty_n;
wire    img_resized_cols_V_channel_read;
wire    img_resized_cols_V_channel1_U_ap_dummy_ce;
wire   [11:0] img_resized_cols_V_channel1_din;
wire    img_resized_cols_V_channel1_write;
wire   [11:0] img_resized_cols_V_channel1_dout;
wire    img_resized_cols_V_channel1_empty_n;
wire    img_resized_cols_V_channel1_read;
wire    img_0_2_rows_V_channel_U_ap_dummy_ce;
wire   [11:0] img_0_2_rows_V_channel_din;
wire    img_0_2_rows_V_channel_write;
wire   [11:0] img_0_2_rows_V_channel_dout;
wire    img_0_2_rows_V_channel_empty_n;
wire    img_0_2_rows_V_channel_read;
wire    img_0_2_cols_V_channel_U_ap_dummy_ce;
wire   [11:0] img_0_2_cols_V_channel_din;
wire    img_0_2_cols_V_channel_write;
wire   [11:0] img_0_2_cols_V_channel_dout;
wire    img_0_2_cols_V_channel_empty_n;
wire    img_0_2_cols_V_channel_read;
wire    img_0_1_data_stream_0_V_U_ap_dummy_ce;
wire   [31:0] img_0_1_data_stream_0_V_din;
wire    img_0_1_data_stream_0_V_full_n;
wire    img_0_1_data_stream_0_V_write;
wire   [31:0] img_0_1_data_stream_0_V_dout;
wire    img_0_1_data_stream_0_V_empty_n;
wire    img_0_1_data_stream_0_V_read;
wire    img_0_2_data_stream_0_V_U_ap_dummy_ce;
wire   [31:0] img_0_2_data_stream_0_V_din;
wire    img_0_2_data_stream_0_V_full_n;
wire    img_0_2_data_stream_0_V_write;
wire   [31:0] img_0_2_data_stream_0_V_dout;
wire    img_0_2_data_stream_0_V_empty_n;
wire    img_0_2_data_stream_0_V_read;
wire    img_resized_data_stream_0_V_U_ap_dummy_ce;
wire   [31:0] img_resized_data_stream_0_V_din;
wire    img_resized_data_stream_0_V_full_n;
wire    img_resized_data_stream_0_V_write;
wire   [31:0] img_resized_data_stream_0_V_dout;
wire    img_resized_data_stream_0_V_empty_n;
wire    img_resized_data_stream_0_V_read;
wire    tmp_loc_channel_U_ap_dummy_ce;
wire   [63:0] tmp_loc_channel_din;
wire    tmp_loc_channel_write;
wire   [63:0] tmp_loc_channel_dout;
wire    tmp_loc_channel_empty_n;
wire    tmp_loc_channel_read;
wire    p_0_i_i_loc_channel_U_ap_dummy_ce;
wire   [31:0] p_0_i_i_loc_channel_din;
wire    p_0_i_i_loc_channel_write;
wire   [31:0] p_0_i_i_loc_channel_dout;
wire    p_0_i_i_loc_channel_empty_n;
wire    p_0_i_i_loc_channel_read;
reg    ap_reg_procdone_image_filter_Block_Mat_exit2020_proc_U0 = 1'b0;
reg    ap_sig_hs_done;
reg    ap_reg_procdone_image_filter_AXIvideo2Mat_32_480_640_5_U0 = 1'b0;
reg    ap_reg_procdone_image_filter_AXIvideo2Mat_32_480_640_5_1_U0 = 1'b0;
reg    ap_reg_procdone_image_filter_Resize_Test_U0 = 1'b0;
reg    ap_reg_procdone_image_filter_Loop_1_proc_U0 = 1'b0;
reg    ap_reg_procdone_image_filter_Block_loopexit24_i_proc1_U0 = 1'b0;
reg    ap_reg_procdone_image_filter_sqrtf1_U0 = 1'b0;
reg    ap_CS;
reg    ap_sig_top_allready;
reg    ap_reg_ready_image_filter_Block_Mat_exit2020_proc_U0_ap_ready = 1'b0;
reg    ap_sig_ready_image_filter_Block_Mat_exit2020_proc_U0_ap_ready;
reg    ap_sig_start_in_image_filter_Block_Mat_exit2020_proc_U0_ap_start;
reg    ap_reg_ready_image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready = 1'b0;
reg    ap_sig_ready_image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready;
reg    ap_sig_start_in_image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_start;
reg    ap_reg_ready_image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready = 1'b0;
reg    ap_sig_ready_image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready;
reg    ap_sig_start_in_image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_start;


image_filter_control_bus_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_BUS_DATA_WIDTH ))
image_filter_control_bus_s_axi_U(
    .AWVALID( s_axi_control_bus_AWVALID ),
    .AWREADY( s_axi_control_bus_AWREADY ),
    .AWADDR( s_axi_control_bus_AWADDR ),
    .WVALID( s_axi_control_bus_WVALID ),
    .WREADY( s_axi_control_bus_WREADY ),
    .WDATA( s_axi_control_bus_WDATA ),
    .WSTRB( s_axi_control_bus_WSTRB ),
    .ARVALID( s_axi_control_bus_ARVALID ),
    .ARREADY( s_axi_control_bus_ARREADY ),
    .ARADDR( s_axi_control_bus_ARADDR ),
    .RVALID( s_axi_control_bus_RVALID ),
    .RREADY( s_axi_control_bus_RREADY ),
    .RDATA( s_axi_control_bus_RDATA ),
    .RRESP( s_axi_control_bus_RRESP ),
    .BVALID( s_axi_control_bus_BVALID ),
    .BREADY( s_axi_control_bus_BREADY ),
    .BRESP( s_axi_control_bus_BRESP ),
    .ACLK( ap_clk ),
    .ARESET( ap_rst_n_inv ),
    .ACLK_EN( image_filter_control_bus_s_axi_U_ap_dummy_ce ),
    .ap_start( ap_start ),
    .interrupt( interrupt ),
    .ap_ready( ap_ready ),
    .ap_done( ap_done ),
    .ap_idle( ap_idle ),
    .ap_return( ap_return ),
    .rows( rows ),
    .cols( cols ),
    .rows2( rows2 ),
    .cols2( cols2 )
);

image_filter_Block_Mat_exit2020_proc image_filter_Block_Mat_exit2020_proc_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( image_filter_Block_Mat_exit2020_proc_U0_ap_start ),
    .ap_done( image_filter_Block_Mat_exit2020_proc_U0_ap_done ),
    .ap_continue( image_filter_Block_Mat_exit2020_proc_U0_ap_continue ),
    .ap_idle( image_filter_Block_Mat_exit2020_proc_U0_ap_idle ),
    .ap_ready( image_filter_Block_Mat_exit2020_proc_U0_ap_ready ),
    .rows( image_filter_Block_Mat_exit2020_proc_U0_rows ),
    .cols( image_filter_Block_Mat_exit2020_proc_U0_cols ),
    .rows2( image_filter_Block_Mat_exit2020_proc_U0_rows2 ),
    .cols2( image_filter_Block_Mat_exit2020_proc_U0_cols2 ),
    .ap_return_0( image_filter_Block_Mat_exit2020_proc_U0_ap_return_0 ),
    .ap_return_1( image_filter_Block_Mat_exit2020_proc_U0_ap_return_1 ),
    .ap_return_2( image_filter_Block_Mat_exit2020_proc_U0_ap_return_2 ),
    .ap_return_3( image_filter_Block_Mat_exit2020_proc_U0_ap_return_3 ),
    .ap_return_4( image_filter_Block_Mat_exit2020_proc_U0_ap_return_4 ),
    .ap_return_5( image_filter_Block_Mat_exit2020_proc_U0_ap_return_5 ),
    .ap_return_6( image_filter_Block_Mat_exit2020_proc_U0_ap_return_6 ),
    .ap_return_7( image_filter_Block_Mat_exit2020_proc_U0_ap_return_7 ),
    .ap_return_8( image_filter_Block_Mat_exit2020_proc_U0_ap_return_8 ),
    .ap_return_9( image_filter_Block_Mat_exit2020_proc_U0_ap_return_9 )
);

image_filter_AXIvideo2Mat_32_480_640_5_s image_filter_AXIvideo2Mat_32_480_640_5_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_start ),
    .ap_done( image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_done ),
    .ap_continue( image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_continue ),
    .ap_idle( image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_idle ),
    .ap_ready( image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready ),
    .input_stream_TDATA( image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TDATA ),
    .input_stream_TVALID( image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TVALID ),
    .input_stream_TREADY( image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TREADY ),
    .input_stream_TKEEP( image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TKEEP ),
    .input_stream_TSTRB( image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TSTRB ),
    .input_stream_TUSER( image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TUSER ),
    .input_stream_TLAST( image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TLAST ),
    .input_stream_TID( image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TID ),
    .input_stream_TDEST( image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TDEST ),
    .img_rows_V_read( image_filter_AXIvideo2Mat_32_480_640_5_U0_img_rows_V_read ),
    .img_cols_V_read( image_filter_AXIvideo2Mat_32_480_640_5_U0_img_cols_V_read ),
    .img_data_stream_V_din( image_filter_AXIvideo2Mat_32_480_640_5_U0_img_data_stream_V_din ),
    .img_data_stream_V_full_n( image_filter_AXIvideo2Mat_32_480_640_5_U0_img_data_stream_V_full_n ),
    .img_data_stream_V_write( image_filter_AXIvideo2Mat_32_480_640_5_U0_img_data_stream_V_write )
);

image_filter_AXIvideo2Mat_32_480_640_5_1 image_filter_AXIvideo2Mat_32_480_640_5_1_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_start ),
    .ap_done( image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_done ),
    .ap_continue( image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_continue ),
    .ap_idle( image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_idle ),
    .ap_ready( image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready ),
    .input2_TDATA( image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TDATA ),
    .input2_TVALID( image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TVALID ),
    .input2_TREADY( image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TREADY ),
    .input2_TKEEP( image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TKEEP ),
    .input2_TSTRB( image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TSTRB ),
    .input2_TUSER( image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TUSER ),
    .input2_TLAST( image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TLAST ),
    .input2_TID( image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TID ),
    .input2_TDEST( image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TDEST ),
    .img_rows_V_read( image_filter_AXIvideo2Mat_32_480_640_5_1_U0_img_rows_V_read ),
    .img_cols_V_read( image_filter_AXIvideo2Mat_32_480_640_5_1_U0_img_cols_V_read ),
    .img_data_stream_V_din( image_filter_AXIvideo2Mat_32_480_640_5_1_U0_img_data_stream_V_din ),
    .img_data_stream_V_full_n( image_filter_AXIvideo2Mat_32_480_640_5_1_U0_img_data_stream_V_full_n ),
    .img_data_stream_V_write( image_filter_AXIvideo2Mat_32_480_640_5_1_U0_img_data_stream_V_write )
);

image_filter_Resize_Test image_filter_Resize_Test_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( image_filter_Resize_Test_U0_ap_start ),
    .ap_done( image_filter_Resize_Test_U0_ap_done ),
    .ap_continue( image_filter_Resize_Test_U0_ap_continue ),
    .ap_idle( image_filter_Resize_Test_U0_ap_idle ),
    .ap_ready( image_filter_Resize_Test_U0_ap_ready ),
    .p_src_rows_V_read( image_filter_Resize_Test_U0_p_src_rows_V_read ),
    .p_src_cols_V_read( image_filter_Resize_Test_U0_p_src_cols_V_read ),
    .p_src_data_stream_V_dout( image_filter_Resize_Test_U0_p_src_data_stream_V_dout ),
    .p_src_data_stream_V_empty_n( image_filter_Resize_Test_U0_p_src_data_stream_V_empty_n ),
    .p_src_data_stream_V_read( image_filter_Resize_Test_U0_p_src_data_stream_V_read ),
    .p_dst_rows_V_read( image_filter_Resize_Test_U0_p_dst_rows_V_read ),
    .p_dst_cols_V_read( image_filter_Resize_Test_U0_p_dst_cols_V_read ),
    .p_dst_data_stream_V_din( image_filter_Resize_Test_U0_p_dst_data_stream_V_din ),
    .p_dst_data_stream_V_full_n( image_filter_Resize_Test_U0_p_dst_data_stream_V_full_n ),
    .p_dst_data_stream_V_write( image_filter_Resize_Test_U0_p_dst_data_stream_V_write )
);

image_filter_Loop_1_proc image_filter_Loop_1_proc_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( image_filter_Loop_1_proc_U0_ap_start ),
    .ap_done( image_filter_Loop_1_proc_U0_ap_done ),
    .ap_continue( image_filter_Loop_1_proc_U0_ap_continue ),
    .ap_idle( image_filter_Loop_1_proc_U0_ap_idle ),
    .ap_ready( image_filter_Loop_1_proc_U0_ap_ready ),
    .img_resized_data_stream_0_V_dout( image_filter_Loop_1_proc_U0_img_resized_data_stream_0_V_dout ),
    .img_resized_data_stream_0_V_empty_n( image_filter_Loop_1_proc_U0_img_resized_data_stream_0_V_empty_n ),
    .img_resized_data_stream_0_V_read( image_filter_Loop_1_proc_U0_img_resized_data_stream_0_V_read ),
    .img_0_2_data_stream_0_V_dout( image_filter_Loop_1_proc_U0_img_0_2_data_stream_0_V_dout ),
    .img_0_2_data_stream_0_V_empty_n( image_filter_Loop_1_proc_U0_img_0_2_data_stream_0_V_empty_n ),
    .img_0_2_data_stream_0_V_read( image_filter_Loop_1_proc_U0_img_0_2_data_stream_0_V_read ),
    .p_read( image_filter_Loop_1_proc_U0_p_read ),
    .p_read1( image_filter_Loop_1_proc_U0_p_read1 ),
    .ap_return( image_filter_Loop_1_proc_U0_ap_return )
);

image_filter_Block_loopexit24_i_proc1 image_filter_Block_loopexit24_i_proc1_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( image_filter_Block_loopexit24_i_proc1_U0_ap_start ),
    .ap_done( image_filter_Block_loopexit24_i_proc1_U0_ap_done ),
    .ap_continue( image_filter_Block_loopexit24_i_proc1_U0_ap_continue ),
    .ap_idle( image_filter_Block_loopexit24_i_proc1_U0_ap_idle ),
    .ap_ready( image_filter_Block_loopexit24_i_proc1_U0_ap_ready ),
    .p_read( image_filter_Block_loopexit24_i_proc1_U0_p_read ),
    .ap_return( image_filter_Block_loopexit24_i_proc1_U0_ap_return )
);

image_filter_sqrtf1 image_filter_sqrtf1_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( image_filter_sqrtf1_U0_ap_start ),
    .ap_done( image_filter_sqrtf1_U0_ap_done ),
    .ap_continue( image_filter_sqrtf1_U0_ap_continue ),
    .ap_idle( image_filter_sqrtf1_U0_ap_idle ),
    .ap_ready( image_filter_sqrtf1_U0_ap_ready ),
    .p_read( image_filter_sqrtf1_U0_p_read ),
    .ap_return( image_filter_sqrtf1_U0_ap_return )
);

FIFO_image_filter_img_0_1_rows_V_channel img_0_1_rows_V_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_1_rows_V_channel_U_ap_dummy_ce ),
    .if_write_ce( img_0_1_rows_V_channel_U_ap_dummy_ce ),
    .if_din( img_0_1_rows_V_channel_din ),
    .if_full_n( img_0_1_rows_V_channel_full_n ),
    .if_write( img_0_1_rows_V_channel_write ),
    .if_dout( img_0_1_rows_V_channel_dout ),
    .if_empty_n( img_0_1_rows_V_channel_empty_n ),
    .if_read( img_0_1_rows_V_channel_read )
);

FIFO_image_filter_img_0_1_rows_V_channel1 img_0_1_rows_V_channel1_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_1_rows_V_channel1_U_ap_dummy_ce ),
    .if_write_ce( img_0_1_rows_V_channel1_U_ap_dummy_ce ),
    .if_din( img_0_1_rows_V_channel1_din ),
    .if_full_n( img_0_1_rows_V_channel1_full_n ),
    .if_write( img_0_1_rows_V_channel1_write ),
    .if_dout( img_0_1_rows_V_channel1_dout ),
    .if_empty_n( img_0_1_rows_V_channel1_empty_n ),
    .if_read( img_0_1_rows_V_channel1_read )
);

FIFO_image_filter_img_0_1_cols_V_channel img_0_1_cols_V_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_1_cols_V_channel_U_ap_dummy_ce ),
    .if_write_ce( img_0_1_cols_V_channel_U_ap_dummy_ce ),
    .if_din( img_0_1_cols_V_channel_din ),
    .if_full_n( img_0_1_cols_V_channel_full_n ),
    .if_write( img_0_1_cols_V_channel_write ),
    .if_dout( img_0_1_cols_V_channel_dout ),
    .if_empty_n( img_0_1_cols_V_channel_empty_n ),
    .if_read( img_0_1_cols_V_channel_read )
);

FIFO_image_filter_img_0_1_cols_V_channel1 img_0_1_cols_V_channel1_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_1_cols_V_channel1_U_ap_dummy_ce ),
    .if_write_ce( img_0_1_cols_V_channel1_U_ap_dummy_ce ),
    .if_din( img_0_1_cols_V_channel1_din ),
    .if_full_n( img_0_1_cols_V_channel1_full_n ),
    .if_write( img_0_1_cols_V_channel1_write ),
    .if_dout( img_0_1_cols_V_channel1_dout ),
    .if_empty_n( img_0_1_cols_V_channel1_empty_n ),
    .if_read( img_0_1_cols_V_channel1_read )
);

FIFO_image_filter_img_resized_rows_V_channel img_resized_rows_V_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_resized_rows_V_channel_U_ap_dummy_ce ),
    .if_write_ce( img_resized_rows_V_channel_U_ap_dummy_ce ),
    .if_din( img_resized_rows_V_channel_din ),
    .if_full_n( img_resized_rows_V_channel_full_n ),
    .if_write( img_resized_rows_V_channel_write ),
    .if_dout( img_resized_rows_V_channel_dout ),
    .if_empty_n( img_resized_rows_V_channel_empty_n ),
    .if_read( img_resized_rows_V_channel_read )
);

FIFO_image_filter_img_resized_rows_V_channel1 img_resized_rows_V_channel1_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_resized_rows_V_channel1_U_ap_dummy_ce ),
    .if_write_ce( img_resized_rows_V_channel1_U_ap_dummy_ce ),
    .if_din( img_resized_rows_V_channel1_din ),
    .if_full_n( img_resized_rows_V_channel1_full_n ),
    .if_write( img_resized_rows_V_channel1_write ),
    .if_dout( img_resized_rows_V_channel1_dout ),
    .if_empty_n( img_resized_rows_V_channel1_empty_n ),
    .if_read( img_resized_rows_V_channel1_read )
);

FIFO_image_filter_img_resized_cols_V_channel img_resized_cols_V_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_resized_cols_V_channel_U_ap_dummy_ce ),
    .if_write_ce( img_resized_cols_V_channel_U_ap_dummy_ce ),
    .if_din( img_resized_cols_V_channel_din ),
    .if_full_n( img_resized_cols_V_channel_full_n ),
    .if_write( img_resized_cols_V_channel_write ),
    .if_dout( img_resized_cols_V_channel_dout ),
    .if_empty_n( img_resized_cols_V_channel_empty_n ),
    .if_read( img_resized_cols_V_channel_read )
);

FIFO_image_filter_img_resized_cols_V_channel1 img_resized_cols_V_channel1_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_resized_cols_V_channel1_U_ap_dummy_ce ),
    .if_write_ce( img_resized_cols_V_channel1_U_ap_dummy_ce ),
    .if_din( img_resized_cols_V_channel1_din ),
    .if_full_n( img_resized_cols_V_channel1_full_n ),
    .if_write( img_resized_cols_V_channel1_write ),
    .if_dout( img_resized_cols_V_channel1_dout ),
    .if_empty_n( img_resized_cols_V_channel1_empty_n ),
    .if_read( img_resized_cols_V_channel1_read )
);

FIFO_image_filter_img_0_2_rows_V_channel img_0_2_rows_V_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_2_rows_V_channel_U_ap_dummy_ce ),
    .if_write_ce( img_0_2_rows_V_channel_U_ap_dummy_ce ),
    .if_din( img_0_2_rows_V_channel_din ),
    .if_full_n( img_0_2_rows_V_channel_full_n ),
    .if_write( img_0_2_rows_V_channel_write ),
    .if_dout( img_0_2_rows_V_channel_dout ),
    .if_empty_n( img_0_2_rows_V_channel_empty_n ),
    .if_read( img_0_2_rows_V_channel_read )
);

FIFO_image_filter_img_0_2_cols_V_channel img_0_2_cols_V_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_2_cols_V_channel_U_ap_dummy_ce ),
    .if_write_ce( img_0_2_cols_V_channel_U_ap_dummy_ce ),
    .if_din( img_0_2_cols_V_channel_din ),
    .if_full_n( img_0_2_cols_V_channel_full_n ),
    .if_write( img_0_2_cols_V_channel_write ),
    .if_dout( img_0_2_cols_V_channel_dout ),
    .if_empty_n( img_0_2_cols_V_channel_empty_n ),
    .if_read( img_0_2_cols_V_channel_read )
);

FIFO_image_filter_img_0_1_data_stream_0_V img_0_1_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_1_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( img_0_1_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( img_0_1_data_stream_0_V_din ),
    .if_full_n( img_0_1_data_stream_0_V_full_n ),
    .if_write( img_0_1_data_stream_0_V_write ),
    .if_dout( img_0_1_data_stream_0_V_dout ),
    .if_empty_n( img_0_1_data_stream_0_V_empty_n ),
    .if_read( img_0_1_data_stream_0_V_read )
);

FIFO_image_filter_img_0_2_data_stream_0_V img_0_2_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_2_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( img_0_2_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( img_0_2_data_stream_0_V_din ),
    .if_full_n( img_0_2_data_stream_0_V_full_n ),
    .if_write( img_0_2_data_stream_0_V_write ),
    .if_dout( img_0_2_data_stream_0_V_dout ),
    .if_empty_n( img_0_2_data_stream_0_V_empty_n ),
    .if_read( img_0_2_data_stream_0_V_read )
);

FIFO_image_filter_img_resized_data_stream_0_V img_resized_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_resized_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( img_resized_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( img_resized_data_stream_0_V_din ),
    .if_full_n( img_resized_data_stream_0_V_full_n ),
    .if_write( img_resized_data_stream_0_V_write ),
    .if_dout( img_resized_data_stream_0_V_dout ),
    .if_empty_n( img_resized_data_stream_0_V_empty_n ),
    .if_read( img_resized_data_stream_0_V_read )
);

FIFO_image_filter_tmp_loc_channel tmp_loc_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( tmp_loc_channel_U_ap_dummy_ce ),
    .if_write_ce( tmp_loc_channel_U_ap_dummy_ce ),
    .if_din( tmp_loc_channel_din ),
    .if_full_n( tmp_loc_channel_full_n ),
    .if_write( tmp_loc_channel_write ),
    .if_dout( tmp_loc_channel_dout ),
    .if_empty_n( tmp_loc_channel_empty_n ),
    .if_read( tmp_loc_channel_read )
);

FIFO_image_filter_p_0_i_i_loc_channel p_0_i_i_loc_channel_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( p_0_i_i_loc_channel_U_ap_dummy_ce ),
    .if_write_ce( p_0_i_i_loc_channel_U_ap_dummy_ce ),
    .if_din( p_0_i_i_loc_channel_din ),
    .if_full_n( p_0_i_i_loc_channel_full_n ),
    .if_write( p_0_i_i_loc_channel_write ),
    .if_dout( p_0_i_i_loc_channel_dout ),
    .if_empty_n( p_0_i_i_loc_channel_empty_n ),
    .if_read( p_0_i_i_loc_channel_read )
);



/// ap_reg_procdone_image_filter_AXIvideo2Mat_32_480_640_5_1_U0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_procdone_image_filter_AXIvideo2Mat_32_480_640_5_1_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_image_filter_AXIvideo2Mat_32_480_640_5_1_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_image_filter_AXIvideo2Mat_32_480_640_5_1_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_done)) begin
            ap_reg_procdone_image_filter_AXIvideo2Mat_32_480_640_5_1_U0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_procdone_image_filter_AXIvideo2Mat_32_480_640_5_U0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_procdone_image_filter_AXIvideo2Mat_32_480_640_5_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_image_filter_AXIvideo2Mat_32_480_640_5_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_image_filter_AXIvideo2Mat_32_480_640_5_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_done)) begin
            ap_reg_procdone_image_filter_AXIvideo2Mat_32_480_640_5_U0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_procdone_image_filter_Block_Mat_exit2020_proc_U0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_procdone_image_filter_Block_Mat_exit2020_proc_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_image_filter_Block_Mat_exit2020_proc_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_image_filter_Block_Mat_exit2020_proc_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_done)) begin
            ap_reg_procdone_image_filter_Block_Mat_exit2020_proc_U0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_procdone_image_filter_Block_loopexit24_i_proc1_U0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_procdone_image_filter_Block_loopexit24_i_proc1_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_image_filter_Block_loopexit24_i_proc1_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_image_filter_Block_loopexit24_i_proc1_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == image_filter_Block_loopexit24_i_proc1_U0_ap_done)) begin
            ap_reg_procdone_image_filter_Block_loopexit24_i_proc1_U0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_procdone_image_filter_Loop_1_proc_U0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_procdone_image_filter_Loop_1_proc_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_image_filter_Loop_1_proc_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_image_filter_Loop_1_proc_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == image_filter_Loop_1_proc_U0_ap_done)) begin
            ap_reg_procdone_image_filter_Loop_1_proc_U0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_procdone_image_filter_Resize_Test_U0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_procdone_image_filter_Resize_Test_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_image_filter_Resize_Test_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_image_filter_Resize_Test_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == image_filter_Resize_Test_U0_ap_done)) begin
            ap_reg_procdone_image_filter_Resize_Test_U0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_procdone_image_filter_sqrtf1_U0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_procdone_image_filter_sqrtf1_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_image_filter_sqrtf1_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_image_filter_sqrtf1_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == image_filter_sqrtf1_U0_ap_done)) begin
            ap_reg_procdone_image_filter_sqrtf1_U0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ready_image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_top_allready))) begin
            ap_reg_ready_image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready)) begin
            ap_reg_ready_image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ready_image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_top_allready))) begin
            ap_reg_ready_image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready)) begin
            ap_reg_ready_image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_image_filter_Block_Mat_exit2020_proc_U0_ap_ready assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ready_image_filter_Block_Mat_exit2020_proc_U0_ap_ready
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_image_filter_Block_Mat_exit2020_proc_U0_ap_ready <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_top_allready))) begin
            ap_reg_ready_image_filter_Block_Mat_exit2020_proc_U0_ap_ready <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_ready)) begin
            ap_reg_ready_image_filter_Block_Mat_exit2020_proc_U0_ap_ready <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_img_0_1_cols_V_channel1_full_n assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ready_img_0_1_cols_V_channel1_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_img_0_1_cols_V_channel1_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_done) & (ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_continue))) begin
            ap_reg_ready_img_0_1_cols_V_channel1_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_done) & (ap_const_logic_1 == img_0_1_cols_V_channel1_full_n))) begin
            ap_reg_ready_img_0_1_cols_V_channel1_full_n <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_img_0_1_cols_V_channel_full_n assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ready_img_0_1_cols_V_channel_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_img_0_1_cols_V_channel_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_done) & (ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_continue))) begin
            ap_reg_ready_img_0_1_cols_V_channel_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_done) & (ap_const_logic_1 == img_0_1_cols_V_channel_full_n))) begin
            ap_reg_ready_img_0_1_cols_V_channel_full_n <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_img_0_1_rows_V_channel1_full_n assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ready_img_0_1_rows_V_channel1_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_img_0_1_rows_V_channel1_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_done) & (ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_continue))) begin
            ap_reg_ready_img_0_1_rows_V_channel1_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_done) & (ap_const_logic_1 == img_0_1_rows_V_channel1_full_n))) begin
            ap_reg_ready_img_0_1_rows_V_channel1_full_n <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_img_0_1_rows_V_channel_full_n assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ready_img_0_1_rows_V_channel_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_img_0_1_rows_V_channel_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_done) & (ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_continue))) begin
            ap_reg_ready_img_0_1_rows_V_channel_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_done) & (ap_const_logic_1 == img_0_1_rows_V_channel_full_n))) begin
            ap_reg_ready_img_0_1_rows_V_channel_full_n <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_img_0_2_cols_V_channel_full_n assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ready_img_0_2_cols_V_channel_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_img_0_2_cols_V_channel_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_done) & (ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_continue))) begin
            ap_reg_ready_img_0_2_cols_V_channel_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_done) & (ap_const_logic_1 == img_0_2_cols_V_channel_full_n))) begin
            ap_reg_ready_img_0_2_cols_V_channel_full_n <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_img_0_2_rows_V_channel_full_n assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ready_img_0_2_rows_V_channel_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_img_0_2_rows_V_channel_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_done) & (ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_continue))) begin
            ap_reg_ready_img_0_2_rows_V_channel_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_done) & (ap_const_logic_1 == img_0_2_rows_V_channel_full_n))) begin
            ap_reg_ready_img_0_2_rows_V_channel_full_n <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_img_resized_cols_V_channel1_full_n assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ready_img_resized_cols_V_channel1_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_img_resized_cols_V_channel1_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_done) & (ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_continue))) begin
            ap_reg_ready_img_resized_cols_V_channel1_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_done) & (ap_const_logic_1 == img_resized_cols_V_channel1_full_n))) begin
            ap_reg_ready_img_resized_cols_V_channel1_full_n <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_img_resized_cols_V_channel_full_n assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ready_img_resized_cols_V_channel_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_img_resized_cols_V_channel_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_done) & (ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_continue))) begin
            ap_reg_ready_img_resized_cols_V_channel_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_done) & (ap_const_logic_1 == img_resized_cols_V_channel_full_n))) begin
            ap_reg_ready_img_resized_cols_V_channel_full_n <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_img_resized_rows_V_channel1_full_n assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ready_img_resized_rows_V_channel1_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_img_resized_rows_V_channel1_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_done) & (ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_continue))) begin
            ap_reg_ready_img_resized_rows_V_channel1_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_done) & (ap_const_logic_1 == img_resized_rows_V_channel1_full_n))) begin
            ap_reg_ready_img_resized_rows_V_channel1_full_n <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ready_img_resized_rows_V_channel_full_n assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ready_img_resized_rows_V_channel_full_n
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ready_img_resized_rows_V_channel_full_n <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_done) & (ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_continue))) begin
            ap_reg_ready_img_resized_rows_V_channel_full_n <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_done) & (ap_const_logic_1 == img_resized_rows_V_channel_full_n))) begin
            ap_reg_ready_img_resized_rows_V_channel_full_n <= ap_const_logic_1;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    ap_CS <= ap_const_logic_0;
end

/// ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_1_cols_V_channel assign process. ///
always @ (image_filter_Block_Mat_exit2020_proc_U0_ap_done or ap_reg_ready_img_0_1_cols_V_channel_full_n)
begin
    if ((ap_const_logic_1 == ap_reg_ready_img_0_1_cols_V_channel_full_n)) begin
        ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_1_cols_V_channel = ap_const_logic_0;
    end else begin
        ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_1_cols_V_channel = image_filter_Block_Mat_exit2020_proc_U0_ap_done;
    end
end

/// ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_1_cols_V_channel1 assign process. ///
always @ (image_filter_Block_Mat_exit2020_proc_U0_ap_done or ap_reg_ready_img_0_1_cols_V_channel1_full_n)
begin
    if ((ap_const_logic_1 == ap_reg_ready_img_0_1_cols_V_channel1_full_n)) begin
        ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_1_cols_V_channel1 = ap_const_logic_0;
    end else begin
        ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_1_cols_V_channel1 = image_filter_Block_Mat_exit2020_proc_U0_ap_done;
    end
end

/// ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_1_rows_V_channel assign process. ///
always @ (image_filter_Block_Mat_exit2020_proc_U0_ap_done or ap_reg_ready_img_0_1_rows_V_channel_full_n)
begin
    if ((ap_const_logic_1 == ap_reg_ready_img_0_1_rows_V_channel_full_n)) begin
        ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_1_rows_V_channel = ap_const_logic_0;
    end else begin
        ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_1_rows_V_channel = image_filter_Block_Mat_exit2020_proc_U0_ap_done;
    end
end

/// ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_1_rows_V_channel1 assign process. ///
always @ (image_filter_Block_Mat_exit2020_proc_U0_ap_done or ap_reg_ready_img_0_1_rows_V_channel1_full_n)
begin
    if ((ap_const_logic_1 == ap_reg_ready_img_0_1_rows_V_channel1_full_n)) begin
        ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_1_rows_V_channel1 = ap_const_logic_0;
    end else begin
        ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_1_rows_V_channel1 = image_filter_Block_Mat_exit2020_proc_U0_ap_done;
    end
end

/// ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_2_cols_V_channel assign process. ///
always @ (image_filter_Block_Mat_exit2020_proc_U0_ap_done or ap_reg_ready_img_0_2_cols_V_channel_full_n)
begin
    if ((ap_const_logic_1 == ap_reg_ready_img_0_2_cols_V_channel_full_n)) begin
        ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_2_cols_V_channel = ap_const_logic_0;
    end else begin
        ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_2_cols_V_channel = image_filter_Block_Mat_exit2020_proc_U0_ap_done;
    end
end

/// ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_2_rows_V_channel assign process. ///
always @ (image_filter_Block_Mat_exit2020_proc_U0_ap_done or ap_reg_ready_img_0_2_rows_V_channel_full_n)
begin
    if ((ap_const_logic_1 == ap_reg_ready_img_0_2_rows_V_channel_full_n)) begin
        ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_2_rows_V_channel = ap_const_logic_0;
    end else begin
        ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_2_rows_V_channel = image_filter_Block_Mat_exit2020_proc_U0_ap_done;
    end
end

/// ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_resized_cols_V_channel assign process. ///
always @ (image_filter_Block_Mat_exit2020_proc_U0_ap_done or ap_reg_ready_img_resized_cols_V_channel_full_n)
begin
    if ((ap_const_logic_1 == ap_reg_ready_img_resized_cols_V_channel_full_n)) begin
        ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_resized_cols_V_channel = ap_const_logic_0;
    end else begin
        ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_resized_cols_V_channel = image_filter_Block_Mat_exit2020_proc_U0_ap_done;
    end
end

/// ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_resized_cols_V_channel1 assign process. ///
always @ (image_filter_Block_Mat_exit2020_proc_U0_ap_done or ap_reg_ready_img_resized_cols_V_channel1_full_n)
begin
    if ((ap_const_logic_1 == ap_reg_ready_img_resized_cols_V_channel1_full_n)) begin
        ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_resized_cols_V_channel1 = ap_const_logic_0;
    end else begin
        ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_resized_cols_V_channel1 = image_filter_Block_Mat_exit2020_proc_U0_ap_done;
    end
end

/// ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_resized_rows_V_channel assign process. ///
always @ (image_filter_Block_Mat_exit2020_proc_U0_ap_done or ap_reg_ready_img_resized_rows_V_channel_full_n)
begin
    if ((ap_const_logic_1 == ap_reg_ready_img_resized_rows_V_channel_full_n)) begin
        ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_resized_rows_V_channel = ap_const_logic_0;
    end else begin
        ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_resized_rows_V_channel = image_filter_Block_Mat_exit2020_proc_U0_ap_done;
    end
end

/// ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_resized_rows_V_channel1 assign process. ///
always @ (image_filter_Block_Mat_exit2020_proc_U0_ap_done or ap_reg_ready_img_resized_rows_V_channel1_full_n)
begin
    if ((ap_const_logic_1 == ap_reg_ready_img_resized_rows_V_channel1_full_n)) begin
        ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_resized_rows_V_channel1 = ap_const_logic_0;
    end else begin
        ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_resized_rows_V_channel1 = image_filter_Block_Mat_exit2020_proc_U0_ap_done;
    end
end

/// ap_idle assign process. ///
always @ (image_filter_Block_Mat_exit2020_proc_U0_ap_idle or image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_idle or image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_idle or image_filter_Resize_Test_U0_ap_idle or image_filter_Loop_1_proc_U0_ap_idle or image_filter_Block_loopexit24_i_proc1_U0_ap_idle or image_filter_sqrtf1_U0_ap_idle or img_0_1_rows_V_channel_empty_n or img_0_1_rows_V_channel1_empty_n or img_0_1_cols_V_channel_empty_n or img_0_1_cols_V_channel1_empty_n or img_resized_rows_V_channel_empty_n or img_resized_rows_V_channel1_empty_n or img_resized_cols_V_channel_empty_n or img_resized_cols_V_channel1_empty_n or img_0_2_rows_V_channel_empty_n or img_0_2_cols_V_channel_empty_n or tmp_loc_channel_empty_n or p_0_i_i_loc_channel_empty_n)
begin
    if (((ap_const_logic_1 == image_filter_Block_Mat_exit2020_proc_U0_ap_idle) & (ap_const_logic_1 == image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_idle) & (ap_const_logic_1 == image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_idle) & (ap_const_logic_1 == image_filter_Resize_Test_U0_ap_idle) & (ap_const_logic_1 == image_filter_Loop_1_proc_U0_ap_idle) & (ap_const_logic_1 == image_filter_Block_loopexit24_i_proc1_U0_ap_idle) & (ap_const_logic_1 == image_filter_sqrtf1_U0_ap_idle) & (ap_const_logic_0 == img_0_1_rows_V_channel_empty_n) & (ap_const_logic_0 == img_0_1_rows_V_channel1_empty_n) & (ap_const_logic_0 == img_0_1_cols_V_channel_empty_n) & (ap_const_logic_0 == img_0_1_cols_V_channel1_empty_n) & (ap_const_logic_0 == img_resized_rows_V_channel_empty_n) & (ap_const_logic_0 == img_resized_rows_V_channel1_empty_n) & (ap_const_logic_0 == img_resized_cols_V_channel_empty_n) & (ap_const_logic_0 == img_resized_cols_V_channel1_empty_n) & (ap_const_logic_0 == img_0_2_rows_V_channel_empty_n) & (ap_const_logic_0 == img_0_2_cols_V_channel_empty_n) & (ap_const_logic_0 == tmp_loc_channel_empty_n) & (ap_const_logic_0 == p_0_i_i_loc_channel_empty_n))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_sig_hs_done assign process. ///
always @ (image_filter_sqrtf1_U0_ap_done)
begin
    if ((ap_const_logic_1 == image_filter_sqrtf1_U0_ap_done)) begin
        ap_sig_hs_done = ap_const_logic_1;
    end else begin
        ap_sig_hs_done = ap_const_logic_0;
    end
end

/// ap_sig_ready_image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready assign process. ///
always @ (image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready or ap_reg_ready_image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready)
begin
    if ((ap_const_logic_0 == ap_reg_ready_image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready)) begin
        ap_sig_ready_image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready = image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready;
    end else begin
        ap_sig_ready_image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready = ap_const_logic_1;
    end
end

/// ap_sig_ready_image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready assign process. ///
always @ (image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready or ap_reg_ready_image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready)
begin
    if ((ap_const_logic_0 == ap_reg_ready_image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready)) begin
        ap_sig_ready_image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready = image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready;
    end else begin
        ap_sig_ready_image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready = ap_const_logic_1;
    end
end

/// ap_sig_ready_image_filter_Block_Mat_exit2020_proc_U0_ap_ready assign process. ///
always @ (image_filter_Block_Mat_exit2020_proc_U0_ap_ready or ap_reg_ready_image_filter_Block_Mat_exit2020_proc_U0_ap_ready)
begin
    if ((ap_const_logic_0 == ap_reg_ready_image_filter_Block_Mat_exit2020_proc_U0_ap_ready)) begin
        ap_sig_ready_image_filter_Block_Mat_exit2020_proc_U0_ap_ready = image_filter_Block_Mat_exit2020_proc_U0_ap_ready;
    end else begin
        ap_sig_ready_image_filter_Block_Mat_exit2020_proc_U0_ap_ready = ap_const_logic_1;
    end
end

/// ap_sig_ready_img_0_1_cols_V_channel1_full_n assign process. ///
always @ (img_0_1_cols_V_channel1_full_n or ap_reg_ready_img_0_1_cols_V_channel1_full_n)
begin
    if ((ap_const_logic_0 == ap_reg_ready_img_0_1_cols_V_channel1_full_n)) begin
        ap_sig_ready_img_0_1_cols_V_channel1_full_n = img_0_1_cols_V_channel1_full_n;
    end else begin
        ap_sig_ready_img_0_1_cols_V_channel1_full_n = ap_const_logic_1;
    end
end

/// ap_sig_ready_img_0_1_cols_V_channel_full_n assign process. ///
always @ (img_0_1_cols_V_channel_full_n or ap_reg_ready_img_0_1_cols_V_channel_full_n)
begin
    if ((ap_const_logic_0 == ap_reg_ready_img_0_1_cols_V_channel_full_n)) begin
        ap_sig_ready_img_0_1_cols_V_channel_full_n = img_0_1_cols_V_channel_full_n;
    end else begin
        ap_sig_ready_img_0_1_cols_V_channel_full_n = ap_const_logic_1;
    end
end

/// ap_sig_ready_img_0_1_rows_V_channel1_full_n assign process. ///
always @ (img_0_1_rows_V_channel1_full_n or ap_reg_ready_img_0_1_rows_V_channel1_full_n)
begin
    if ((ap_const_logic_0 == ap_reg_ready_img_0_1_rows_V_channel1_full_n)) begin
        ap_sig_ready_img_0_1_rows_V_channel1_full_n = img_0_1_rows_V_channel1_full_n;
    end else begin
        ap_sig_ready_img_0_1_rows_V_channel1_full_n = ap_const_logic_1;
    end
end

/// ap_sig_ready_img_0_1_rows_V_channel_full_n assign process. ///
always @ (img_0_1_rows_V_channel_full_n or ap_reg_ready_img_0_1_rows_V_channel_full_n)
begin
    if ((ap_const_logic_0 == ap_reg_ready_img_0_1_rows_V_channel_full_n)) begin
        ap_sig_ready_img_0_1_rows_V_channel_full_n = img_0_1_rows_V_channel_full_n;
    end else begin
        ap_sig_ready_img_0_1_rows_V_channel_full_n = ap_const_logic_1;
    end
end

/// ap_sig_ready_img_0_2_cols_V_channel_full_n assign process. ///
always @ (img_0_2_cols_V_channel_full_n or ap_reg_ready_img_0_2_cols_V_channel_full_n)
begin
    if ((ap_const_logic_0 == ap_reg_ready_img_0_2_cols_V_channel_full_n)) begin
        ap_sig_ready_img_0_2_cols_V_channel_full_n = img_0_2_cols_V_channel_full_n;
    end else begin
        ap_sig_ready_img_0_2_cols_V_channel_full_n = ap_const_logic_1;
    end
end

/// ap_sig_ready_img_0_2_rows_V_channel_full_n assign process. ///
always @ (img_0_2_rows_V_channel_full_n or ap_reg_ready_img_0_2_rows_V_channel_full_n)
begin
    if ((ap_reg_ready_img_0_2_rows_V_channel_full_n == ap_const_logic_0)) begin
        ap_sig_ready_img_0_2_rows_V_channel_full_n = img_0_2_rows_V_channel_full_n;
    end else begin
        ap_sig_ready_img_0_2_rows_V_channel_full_n = ap_const_logic_1;
    end
end

/// ap_sig_ready_img_resized_cols_V_channel1_full_n assign process. ///
always @ (img_resized_cols_V_channel1_full_n or ap_reg_ready_img_resized_cols_V_channel1_full_n)
begin
    if ((ap_const_logic_0 == ap_reg_ready_img_resized_cols_V_channel1_full_n)) begin
        ap_sig_ready_img_resized_cols_V_channel1_full_n = img_resized_cols_V_channel1_full_n;
    end else begin
        ap_sig_ready_img_resized_cols_V_channel1_full_n = ap_const_logic_1;
    end
end

/// ap_sig_ready_img_resized_cols_V_channel_full_n assign process. ///
always @ (img_resized_cols_V_channel_full_n or ap_reg_ready_img_resized_cols_V_channel_full_n)
begin
    if ((ap_const_logic_0 == ap_reg_ready_img_resized_cols_V_channel_full_n)) begin
        ap_sig_ready_img_resized_cols_V_channel_full_n = img_resized_cols_V_channel_full_n;
    end else begin
        ap_sig_ready_img_resized_cols_V_channel_full_n = ap_const_logic_1;
    end
end

/// ap_sig_ready_img_resized_rows_V_channel1_full_n assign process. ///
always @ (img_resized_rows_V_channel1_full_n or ap_reg_ready_img_resized_rows_V_channel1_full_n)
begin
    if ((ap_const_logic_0 == ap_reg_ready_img_resized_rows_V_channel1_full_n)) begin
        ap_sig_ready_img_resized_rows_V_channel1_full_n = img_resized_rows_V_channel1_full_n;
    end else begin
        ap_sig_ready_img_resized_rows_V_channel1_full_n = ap_const_logic_1;
    end
end

/// ap_sig_ready_img_resized_rows_V_channel_full_n assign process. ///
always @ (img_resized_rows_V_channel_full_n or ap_reg_ready_img_resized_rows_V_channel_full_n)
begin
    if ((ap_const_logic_0 == ap_reg_ready_img_resized_rows_V_channel_full_n)) begin
        ap_sig_ready_img_resized_rows_V_channel_full_n = img_resized_rows_V_channel_full_n;
    end else begin
        ap_sig_ready_img_resized_rows_V_channel_full_n = ap_const_logic_1;
    end
end

/// ap_sig_start_in_image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_start assign process. ///
always @ (ap_start or ap_reg_ready_image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready)
begin
    if (((ap_const_logic_1 == ap_start) & (ap_const_logic_0 == ap_reg_ready_image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready))) begin
        ap_sig_start_in_image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_start = ap_const_logic_1;
    end else begin
        ap_sig_start_in_image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_start = ap_const_logic_0;
    end
end

/// ap_sig_start_in_image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_start assign process. ///
always @ (ap_start or ap_reg_ready_image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready)
begin
    if (((ap_const_logic_1 == ap_start) & (ap_const_logic_0 == ap_reg_ready_image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready))) begin
        ap_sig_start_in_image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_start = ap_const_logic_1;
    end else begin
        ap_sig_start_in_image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_start = ap_const_logic_0;
    end
end

/// ap_sig_start_in_image_filter_Block_Mat_exit2020_proc_U0_ap_start assign process. ///
always @ (ap_start or ap_reg_ready_image_filter_Block_Mat_exit2020_proc_U0_ap_ready)
begin
    if (((ap_const_logic_0 == ap_reg_ready_image_filter_Block_Mat_exit2020_proc_U0_ap_ready) & (ap_const_logic_1 == ap_start))) begin
        ap_sig_start_in_image_filter_Block_Mat_exit2020_proc_U0_ap_start = ap_const_logic_1;
    end else begin
        ap_sig_start_in_image_filter_Block_Mat_exit2020_proc_U0_ap_start = ap_const_logic_0;
    end
end

/// ap_sig_top_allready assign process. ///
always @ (ap_sig_ready_image_filter_Block_Mat_exit2020_proc_U0_ap_ready or ap_sig_ready_image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready or ap_sig_ready_image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready)
begin
    if (((ap_const_logic_1 == ap_sig_ready_image_filter_Block_Mat_exit2020_proc_U0_ap_ready) & (ap_const_logic_1 == ap_sig_ready_image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready) & (ap_const_logic_1 == ap_sig_ready_image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready))) begin
        ap_sig_top_allready = ap_const_logic_1;
    end else begin
        ap_sig_top_allready = ap_const_logic_0;
    end
end

/// image_filter_Block_Mat_exit2020_proc_U0_ap_continue assign process. ///
always @ (ap_sig_ready_img_0_2_rows_V_channel_full_n or ap_sig_ready_img_0_1_rows_V_channel_full_n or ap_sig_ready_img_0_1_rows_V_channel1_full_n or ap_sig_ready_img_0_1_cols_V_channel_full_n or ap_sig_ready_img_resized_cols_V_channel1_full_n or ap_sig_ready_img_0_1_cols_V_channel1_full_n or ap_sig_ready_img_resized_rows_V_channel_full_n or ap_sig_ready_img_resized_rows_V_channel1_full_n or ap_sig_ready_img_resized_cols_V_channel_full_n or ap_sig_ready_img_0_2_cols_V_channel_full_n)
begin
    if (((ap_const_logic_1 == ap_sig_ready_img_0_2_rows_V_channel_full_n) & (ap_const_logic_1 == ap_sig_ready_img_0_1_rows_V_channel_full_n) & (ap_const_logic_1 == ap_sig_ready_img_0_1_rows_V_channel1_full_n) & (ap_const_logic_1 == ap_sig_ready_img_0_1_cols_V_channel_full_n) & (ap_const_logic_1 == ap_sig_ready_img_resized_cols_V_channel1_full_n) & (ap_const_logic_1 == ap_sig_ready_img_0_1_cols_V_channel1_full_n) & (ap_const_logic_1 == ap_sig_ready_img_resized_rows_V_channel_full_n) & (ap_const_logic_1 == ap_sig_ready_img_resized_rows_V_channel1_full_n) & (ap_const_logic_1 == ap_sig_ready_img_resized_cols_V_channel_full_n) & (ap_const_logic_1 == ap_sig_ready_img_0_2_cols_V_channel_full_n))) begin
        image_filter_Block_Mat_exit2020_proc_U0_ap_continue = ap_const_logic_1;
    end else begin
        image_filter_Block_Mat_exit2020_proc_U0_ap_continue = ap_const_logic_0;
    end
end
assign ap_chn_write_image_filter_Block_loopexit24_i_proc1_U0_p_0_i_i_loc_channel = image_filter_Block_loopexit24_i_proc1_U0_ap_done;
assign ap_chn_write_image_filter_Loop_1_proc_U0_tmp_loc_channel = image_filter_Loop_1_proc_U0_ap_done;
assign ap_done = ap_sig_hs_done;
assign ap_ready = ap_sig_top_allready;
assign ap_return = image_filter_sqrtf1_U0_ap_return;

/// ap_rst_n_inv assign process. ///
always @ (ap_rst_n)
begin
    ap_rst_n_inv = ~ap_rst_n;
end
assign ap_sig_hs_continue = ap_const_logic_1;
assign image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_continue = ap_const_logic_1;
assign image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_start = (img_0_2_rows_V_channel_empty_n & img_0_2_cols_V_channel_empty_n & ap_sig_start_in_image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_start);
assign image_filter_AXIvideo2Mat_32_480_640_5_1_U0_img_cols_V_read = img_0_2_cols_V_channel_dout;
assign image_filter_AXIvideo2Mat_32_480_640_5_1_U0_img_data_stream_V_full_n = img_0_2_data_stream_0_V_full_n;
assign image_filter_AXIvideo2Mat_32_480_640_5_1_U0_img_rows_V_read = img_0_2_rows_V_channel_dout;
assign image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TDATA = input2_TDATA;
assign image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TDEST = input2_TDEST;
assign image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TID = input2_TID;
assign image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TKEEP = input2_TKEEP;
assign image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TLAST = input2_TLAST;
assign image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TSTRB = input2_TSTRB;
assign image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TUSER = input2_TUSER;
assign image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TVALID = input2_TVALID;
assign image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_continue = ap_const_logic_1;
assign image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_start = (img_0_1_rows_V_channel_empty_n & img_0_1_cols_V_channel_empty_n & ap_sig_start_in_image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_start);
assign image_filter_AXIvideo2Mat_32_480_640_5_U0_img_cols_V_read = img_0_1_cols_V_channel_dout;
assign image_filter_AXIvideo2Mat_32_480_640_5_U0_img_data_stream_V_full_n = img_0_1_data_stream_0_V_full_n;
assign image_filter_AXIvideo2Mat_32_480_640_5_U0_img_rows_V_read = img_0_1_rows_V_channel_dout;
assign image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TDATA = input_stream_TDATA;
assign image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TDEST = input_stream_TDEST;
assign image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TID = input_stream_TID;
assign image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TKEEP = input_stream_TKEEP;
assign image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TLAST = input_stream_TLAST;
assign image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TSTRB = input_stream_TSTRB;
assign image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TUSER = input_stream_TUSER;
assign image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TVALID = input_stream_TVALID;
assign image_filter_Block_Mat_exit2020_proc_U0_ap_start = ap_sig_start_in_image_filter_Block_Mat_exit2020_proc_U0_ap_start;
assign image_filter_Block_Mat_exit2020_proc_U0_cols = cols;
assign image_filter_Block_Mat_exit2020_proc_U0_cols2 = cols2;
assign image_filter_Block_Mat_exit2020_proc_U0_rows = rows;
assign image_filter_Block_Mat_exit2020_proc_U0_rows2 = rows2;
assign image_filter_Block_loopexit24_i_proc1_U0_ap_continue = p_0_i_i_loc_channel_full_n;
assign image_filter_Block_loopexit24_i_proc1_U0_ap_start = tmp_loc_channel_empty_n;
assign image_filter_Block_loopexit24_i_proc1_U0_p_read = tmp_loc_channel_dout;
assign image_filter_Loop_1_proc_U0_ap_continue = tmp_loc_channel_full_n;
assign image_filter_Loop_1_proc_U0_ap_start = (img_resized_rows_V_channel1_empty_n & img_resized_cols_V_channel1_empty_n);
assign image_filter_Loop_1_proc_U0_img_0_2_data_stream_0_V_dout = img_0_2_data_stream_0_V_dout;
assign image_filter_Loop_1_proc_U0_img_0_2_data_stream_0_V_empty_n = img_0_2_data_stream_0_V_empty_n;
assign image_filter_Loop_1_proc_U0_img_resized_data_stream_0_V_dout = img_resized_data_stream_0_V_dout;
assign image_filter_Loop_1_proc_U0_img_resized_data_stream_0_V_empty_n = img_resized_data_stream_0_V_empty_n;
assign image_filter_Loop_1_proc_U0_p_read = img_resized_cols_V_channel1_dout;
assign image_filter_Loop_1_proc_U0_p_read1 = img_resized_rows_V_channel1_dout;
assign image_filter_Resize_Test_U0_ap_continue = ap_const_logic_1;
assign image_filter_Resize_Test_U0_ap_start = (img_0_1_rows_V_channel1_empty_n & img_0_1_cols_V_channel1_empty_n & img_resized_rows_V_channel_empty_n & img_resized_cols_V_channel_empty_n);
assign image_filter_Resize_Test_U0_p_dst_cols_V_read = img_resized_cols_V_channel_dout;
assign image_filter_Resize_Test_U0_p_dst_data_stream_V_full_n = img_resized_data_stream_0_V_full_n;
assign image_filter_Resize_Test_U0_p_dst_rows_V_read = img_resized_rows_V_channel_dout;
assign image_filter_Resize_Test_U0_p_src_cols_V_read = img_0_1_cols_V_channel1_dout;
assign image_filter_Resize_Test_U0_p_src_data_stream_V_dout = img_0_1_data_stream_0_V_dout;
assign image_filter_Resize_Test_U0_p_src_data_stream_V_empty_n = img_0_1_data_stream_0_V_empty_n;
assign image_filter_Resize_Test_U0_p_src_rows_V_read = img_0_1_rows_V_channel1_dout;
assign image_filter_control_bus_s_axi_U_ap_dummy_ce = ap_const_logic_1;
assign image_filter_sqrtf1_U0_ap_continue = ap_sig_hs_continue;
assign image_filter_sqrtf1_U0_ap_start = p_0_i_i_loc_channel_empty_n;
assign image_filter_sqrtf1_U0_p_read = p_0_i_i_loc_channel_dout;
assign img_0_1_cols_V_channel1_U_ap_dummy_ce = ap_const_logic_1;
assign img_0_1_cols_V_channel1_din = image_filter_Block_Mat_exit2020_proc_U0_ap_return_3;
assign img_0_1_cols_V_channel1_read = image_filter_Resize_Test_U0_ap_ready;
assign img_0_1_cols_V_channel1_write = ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_1_cols_V_channel1;
assign img_0_1_cols_V_channel_U_ap_dummy_ce = ap_const_logic_1;
assign img_0_1_cols_V_channel_din = image_filter_Block_Mat_exit2020_proc_U0_ap_return_2;
assign img_0_1_cols_V_channel_read = image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready;
assign img_0_1_cols_V_channel_write = ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_1_cols_V_channel;
assign img_0_1_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;
assign img_0_1_data_stream_0_V_din = image_filter_AXIvideo2Mat_32_480_640_5_U0_img_data_stream_V_din;
assign img_0_1_data_stream_0_V_read = image_filter_Resize_Test_U0_p_src_data_stream_V_read;
assign img_0_1_data_stream_0_V_write = image_filter_AXIvideo2Mat_32_480_640_5_U0_img_data_stream_V_write;
assign img_0_1_rows_V_channel1_U_ap_dummy_ce = ap_const_logic_1;
assign img_0_1_rows_V_channel1_din = image_filter_Block_Mat_exit2020_proc_U0_ap_return_1;
assign img_0_1_rows_V_channel1_read = image_filter_Resize_Test_U0_ap_ready;
assign img_0_1_rows_V_channel1_write = ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_1_rows_V_channel1;
assign img_0_1_rows_V_channel_U_ap_dummy_ce = ap_const_logic_1;
assign img_0_1_rows_V_channel_din = image_filter_Block_Mat_exit2020_proc_U0_ap_return_0;
assign img_0_1_rows_V_channel_read = image_filter_AXIvideo2Mat_32_480_640_5_U0_ap_ready;
assign img_0_1_rows_V_channel_write = ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_1_rows_V_channel;
assign img_0_2_cols_V_channel_U_ap_dummy_ce = ap_const_logic_1;
assign img_0_2_cols_V_channel_din = image_filter_Block_Mat_exit2020_proc_U0_ap_return_9;
assign img_0_2_cols_V_channel_read = image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready;
assign img_0_2_cols_V_channel_write = ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_2_cols_V_channel;
assign img_0_2_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;
assign img_0_2_data_stream_0_V_din = image_filter_AXIvideo2Mat_32_480_640_5_1_U0_img_data_stream_V_din;
assign img_0_2_data_stream_0_V_read = image_filter_Loop_1_proc_U0_img_0_2_data_stream_0_V_read;
assign img_0_2_data_stream_0_V_write = image_filter_AXIvideo2Mat_32_480_640_5_1_U0_img_data_stream_V_write;
assign img_0_2_rows_V_channel_U_ap_dummy_ce = ap_const_logic_1;
assign img_0_2_rows_V_channel_din = image_filter_Block_Mat_exit2020_proc_U0_ap_return_8;
assign img_0_2_rows_V_channel_read = image_filter_AXIvideo2Mat_32_480_640_5_1_U0_ap_ready;
assign img_0_2_rows_V_channel_write = ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_0_2_rows_V_channel;
assign img_resized_cols_V_channel1_U_ap_dummy_ce = ap_const_logic_1;
assign img_resized_cols_V_channel1_din = image_filter_Block_Mat_exit2020_proc_U0_ap_return_7;
assign img_resized_cols_V_channel1_read = image_filter_Loop_1_proc_U0_ap_ready;
assign img_resized_cols_V_channel1_write = ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_resized_cols_V_channel1;
assign img_resized_cols_V_channel_U_ap_dummy_ce = ap_const_logic_1;
assign img_resized_cols_V_channel_din = image_filter_Block_Mat_exit2020_proc_U0_ap_return_6;
assign img_resized_cols_V_channel_read = image_filter_Resize_Test_U0_ap_ready;
assign img_resized_cols_V_channel_write = ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_resized_cols_V_channel;
assign img_resized_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;
assign img_resized_data_stream_0_V_din = image_filter_Resize_Test_U0_p_dst_data_stream_V_din;
assign img_resized_data_stream_0_V_read = image_filter_Loop_1_proc_U0_img_resized_data_stream_0_V_read;
assign img_resized_data_stream_0_V_write = image_filter_Resize_Test_U0_p_dst_data_stream_V_write;
assign img_resized_rows_V_channel1_U_ap_dummy_ce = ap_const_logic_1;
assign img_resized_rows_V_channel1_din = image_filter_Block_Mat_exit2020_proc_U0_ap_return_5;
assign img_resized_rows_V_channel1_read = image_filter_Loop_1_proc_U0_ap_ready;
assign img_resized_rows_V_channel1_write = ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_resized_rows_V_channel1;
assign img_resized_rows_V_channel_U_ap_dummy_ce = ap_const_logic_1;
assign img_resized_rows_V_channel_din = image_filter_Block_Mat_exit2020_proc_U0_ap_return_4;
assign img_resized_rows_V_channel_read = image_filter_Resize_Test_U0_ap_ready;
assign img_resized_rows_V_channel_write = ap_chn_write_image_filter_Block_Mat_exit2020_proc_U0_img_resized_rows_V_channel;
assign input2_TREADY = image_filter_AXIvideo2Mat_32_480_640_5_1_U0_input2_TREADY;
assign input_stream_TREADY = image_filter_AXIvideo2Mat_32_480_640_5_U0_input_stream_TREADY;
assign p_0_i_i_loc_channel_U_ap_dummy_ce = ap_const_logic_1;
assign p_0_i_i_loc_channel_din = image_filter_Block_loopexit24_i_proc1_U0_ap_return;
assign p_0_i_i_loc_channel_read = image_filter_sqrtf1_U0_ap_ready;
assign p_0_i_i_loc_channel_write = ap_chn_write_image_filter_Block_loopexit24_i_proc1_U0_p_0_i_i_loc_channel;
assign tmp_loc_channel_U_ap_dummy_ce = ap_const_logic_1;
assign tmp_loc_channel_din = image_filter_Loop_1_proc_U0_ap_return;
assign tmp_loc_channel_read = image_filter_Block_loopexit24_i_proc1_U0_ap_ready;
assign tmp_loc_channel_write = ap_chn_write_image_filter_Loop_1_proc_U0_tmp_loc_channel;


endmodule //image_filter

